language: node_js
node_js:
    - "6.0"
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
  - export CHROME_BIN=chromium-browser
before_script:
  - npm install
  - npm install -g webpack
  - npm install -g karma-cli
  - npm install -g jasmine
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
services:
  - mongodb